import type { NormalizedShopifyProduct } from './types';

export const MOCK_PRODUCTS: NormalizedShopifyProduct[] = [
  {
    shopifyId: 'gid://shopify/Product/1001',
    handle: 'black-cargo-pant',
    title: 'Black Cargo Pant',
    productType: 'Bottoms',
    vendor: 're-vice',
    available: true,
    imageUrl: null,
    onlineStoreUrl: null,
    raw: {},
    variants: [
      { shopifyVariantId: 'gid://shopify/ProductVariant/10011', title: 'XS', sku: 'BCP-XS', price: '120.00', currencyCode: 'USD', available: true, position: 0 },
      { shopifyVariantId: 'gid://shopify/ProductVariant/10012', title: 'S', sku: 'BCP-S', price: '120.00', currencyCode: 'USD', available: true, position: 1 },
      { shopifyVariantId: 'gid://shopify/ProductVariant/10013', title: 'M', sku: 'BCP-M', price: '120.00', currencyCode: 'USD', available: false, position: 2 },
    ],
  },
  {
    shopifyId: 'gid://shopify/Product/1002',
    handle: 'oversized-graphic-tee',
    title: 'Oversized Graphic Tee',
    productType: 'Tops',
    vendor: 're-vice',
    available: true,
    imageUrl: null,
    onlineStoreUrl: null,
    raw: {},
    variants: [
      { shopifyVariantId: 'gid://shopify/ProductVariant/10021', title: 'S', sku: 'OGT-S', price: '75.00', currencyCode: 'USD', available: true, position: 0 },
      { shopifyVariantId: 'gid://shopify/ProductVariant/10022', title: 'M', sku: 'OGT-M', price: '75.00', currencyCode: 'USD', available: true, position: 1 },
    ],
  },
  {
    shopifyId: 'gid://shopify/Product/1003',
    handle: 'denim-jacket-washed',
    title: 'Denim Jacket Washed',
    productType: 'Outerwear',
    vendor: 're-vice',
    available: false,
    imageUrl: null,
    onlineStoreUrl: null,
    raw: {},
    variants: [
      { shopifyVariantId: 'gid://shopify/ProductVariant/10031', title: 'S/M', sku: 'DJW-SM', price: '195.00', currencyCode: 'USD', available: false, position: 0 },
    ],
  },
  {
    shopifyId: 'gid://shopify/Product/1004',
    handle: 'crossbody-bag-mini',
    title: 'Crossbody Bag Mini',
    productType: 'Accessories',
    vendor: 're-vice',
    available: true,
    imageUrl: null,
    onlineStoreUrl: null,
    raw: {},
    variants: [
      { shopifyVariantId: 'gid://shopify/ProductVariant/10041', title: 'Black', sku: 'CBM-BLK', price: '145.00', currencyCode: 'USD', available: true, position: 0 },
      { shopifyVariantId: 'gid://shopify/ProductVariant/10042', title: 'White', sku: 'CBM-WHT', price: '145.00', currencyCode: 'USD', available: true, position: 1 },
    ],
  },
  {
    shopifyId: 'gid://shopify/Product/1005',
    handle: 'track-pant-relaxed',
    title: 'Track Pant Relaxed',
    productType: 'Bottoms',
    vendor: 're-vice',
    available: true,
    imageUrl: null,
    onlineStoreUrl: null,
    raw: {},
    variants: [
      { shopifyVariantId: 'gid://shopify/ProductVariant/10051', title: 'XS', sku: 'TPR-XS', price: '110.00', currencyCode: 'USD', available: true, position: 0 },
      { shopifyVariantId: 'gid://shopify/ProductVariant/10052', title: 'S', sku: 'TPR-S', price: '110.00', currencyCode: 'USD', available: true, position: 1 },
      { shopifyVariantId: 'gid://shopify/ProductVariant/10053', title: 'M', sku: 'TPR-M', price: '110.00', currencyCode: 'USD', available: true, position: 2 },
      { shopifyVariantId: 'gid://shopify/ProductVariant/10054', title: 'L', sku: 'TPR-L', price: '110.00', currencyCode: 'USD', available: false, position: 3 },
    ],
  },
];
